"""add_file_type_to_documents

Revision ID: b35f62ae79bf
Revises: c7de9a98cbb3
Create Date: 2026-05-14 11:19:48.844349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35f62ae79bf'
down_revision: Union[str, Sequence[str], None] = 'c7de9a98cbb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('documents', sa.Column('file_type', sa.String(length=16), nullable=True))
    op.execute("UPDATE documents SET file_type = 'txt' WHERE file_type IS NULL")
    op.alter_column('documents', 'file_type', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_type')
    # ### end Alembic commands ###
