"""add is_superuser to users

Revision ID: bb8de6a85198
Revises: 0c6c56803648
Create Date: 2026-04-17 18:20:34.743871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb8de6a85198'
down_revision: Union[str, Sequence[str], None] = '0c6c56803648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加列并允许为空，避免已有数据报错
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # 更新已有数据的 is_superuser 为 False
    op.execute("UPDATE users SET is_superuser = FALSE WHERE is_superuser IS NULL")
    # 然后再将列修改为不允许为空
    op.alter_column('users', 'is_superuser', nullable=False)
    # ### end Alembic commands ######


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###
