"""add user llm config

Revision ID: c7de9a98cbb3
Revises: 5c6f8b7a9d21
Create Date: 2026-05-09 12:54:08.257313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7de9a98cbb3'
down_revision: Union[str, Sequence[str], None] = '5c6f8b7a9d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('llm_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('llm_base_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('llm_model_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('llm_api_key_encrypted', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'llm_api_key_encrypted')
    op.drop_column('users', 'llm_model_name')
    op.drop_column('users', 'llm_base_url')
    op.drop_column('users', 'llm_provider')
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
